import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
function glb(name){const b=readFileSync(new URL(`../public/assets/models/${name}.glb`,import.meta.url));assert.equal(b.readUInt32LE(0),0x46546c67);const n=b.readUInt32LE(12),j=JSON.parse(b.subarray(20,20+n));return {j,binary:b.subarray(28+n)};}
function values(g,index){const a=g.j.accessors[index],v=g.j.bufferViews[a.bufferView],offset=(v.byteOffset||0)+(a.byteOffset||0),width={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT4:16}[a.type];const bytes={5126:4,5123:2,5125:4}[a.componentType],result=[];for(let i=0;i<a.count*width;i++)result.push(g.binary[a.componentType===5126?'readFloatLE':a.componentType===5123?'readUInt16LE':'readUInt32LE'](offset+i*bytes));return result;}
for(const name of ['british','british-v1','british-v2','german','german-v1','german-v2']){
 test(`${name}: refined material resolves all external 2048px textures and the correct faction atlas`,()=>{const {j}=glb(name);const material=j.materials[0],color=j.images[j.textures[material.pbrMetallicRoughness.baseColorTexture.index].source];assert.equal(color.uri,name.startsWith('german')?'textures/infantry-german-refined-color.png':'textures/infantry-refined-color.png');for(const image of j.images){assert.match(image.uri,/^textures\/[^/]+\.png$/);const png=readFileSync(new URL(`../public/assets/models/${image.uri}`,import.meta.url));assert.equal(png.subarray(0,8).toString('hex'),'89504e470d0a1a0a');assert.equal(png.readUInt32BE(16),2048);assert.equal(png.readUInt32BE(20),2048);}});
 test(`${name}: three genuine LOD meshes share textured material and skeleton`,()=>{const {j}=glb(name);assert.equal(j.meshes.length,3);assert.equal(j.skins.length,1);assert.equal(j.skins[0].joints.length,19);assert.equal(j.materials.length,1);assert.equal(j.images.length,3);const mat=j.materials[0];assert.ok(mat.pbrMetallicRoughness.baseColorTexture);assert.ok(mat.pbrMetallicRoughness.metallicRoughnessTexture);assert.ok(mat.normalTexture);for(let i=0;i<3;i++){assert.match(j.meshes[i].name,new RegExp(`lod${i}`));const a=j.meshes[i].primitives[0].attributes;assert.notEqual(a.TEXCOORD_0,undefined);assert.notEqual(a.WEIGHTS_0,undefined);}const n=j.meshes.map(m=>j.accessors[m.primitives[0].indices].count/3);assert.ok(n[0]>5000&&n[0]<25000,`near ${n[0]}`);assert.ok(n[1]<9000&&n[1]<n[0]*.55,`mid ${n[1]}`);assert.ok(n[2]<2500&&n[2]<n[0]*.25,`far ${n[2]}`);});
 test(`${name}: finite metre-scale geometry and normalized blended skin weights`,()=>{const g=glb(name);let blends=0;for(const m of g.j.meshes){const a=m.primitives[0].attributes,positions=values(g,a.POSITION),weights=values(g,a.WEIGHTS_0),joints=values(g,a.JOINTS_0);assert.ok(positions.every(Number.isFinite));const normals=values(g,a.NORMAL);let invalid=0;for(let k=0;k<normals.length;k+=3)if(Math.hypot(...normals.slice(k,k+3))<.90)invalid++;assert.equal(invalid,0,`zero/cancelled surface normals: ${invalid}`);const ys=positions.filter((v,i)=>i%3===1);assert.ok(Math.max(...ys)<1.95);assert.ok(Math.min(...ys)>-.02);for(let i=0;i<weights.length;i+=4){assert.ok(Math.abs(weights.slice(i,i+4).reduce((a,b)=>a+b,0)-1)<1e-5);if(weights[i+1]>.001)blends++;}assert.ok(joints.every(j=>j>=0&&j<19));}assert.ok(blends>100,`blended vertices ${blends}`);});
 test(`${name}: all gameplay clips retained with normalized quaternion samples`,()=>{const g=glb(name);for(const name of ['idle','walk','run','crouch','prone','aim','fire','reload','hit','death','vault','grenade','melee'])assert.ok(g.j.animations.some(a=>a.name===name),name);for(const a of g.j.animations)for(const channel of a.channels){if(channel.target.path!=='rotation')continue;const q=values(g,a.samplers[channel.sampler].output);for(let i=0;i<q.length;i+=4)assert.ok(Math.abs(Math.hypot(...q.slice(i,i+4))-1)<1e-4);}});
}
