import test from 'node:test';import assert from 'node:assert/strict';
import {Simulation} from '../src/core/simulation.js';import {fireBullet,blast} from '../src/combat/ballistics.js';import {updateSoldier} from '../src/ai/soldier.js';import {eye} from '../src/world/collision.js';import {validateSnapshot} from '../src/save/schema.js';
const flat=s=>{s.terrain.height=()=>0;s.collision.boxes=[];s.collision.dynamic=[];s.player.pos={x:0,y:0,z:0};s.player.yaw=0;s.player.pitch=0;};
test('najbliższa przeszkoda blokuje lufę mimo widocznego celu dla kamery',()=>{const s=new Simulation();flat(s);const enemy=s.npcs.find(n=>n.faction==='de');enemy.pos={x:0,y:0,z:8};enemy.stance='stand';s.actors=[s.player,enemy];s.collision.boxes=[{id:'cover',min:{x:-1,y:0,z:.25},max:{x:1,y:1.56,z:.42}}];const intent=s.collision.ray(eye(s.player),{x:0,y:0,z:1},20,[enemy]);assert.equal(intent.actor.id,enemy.id);const hit=fireBullet(s,s.player,s.player.weapon,{x:0,y:0,z:1},0);assert.equal(hit.kind,'solid');assert.equal(enemy.hp,100);});
test('celowanie przez przyrządy nie produkuje NaN i trafia widoczny cel',()=>{const s=new Simulation();flat(s);const enemy=s.npcs.find(n=>n.faction==='de');enemy.pos={x:0,y:0,z:8};s.actors=[s.player,enemy];s.player.update(s,1/60,{aim:true,fire:true});assert.ok(enemy.hp<100);assert.ok(Number.isFinite(s.player.pitch));assert.equal(s.player.weapon.mag,9);});
test('granat respektuje osłonę, a po jej usunięciu zadaje obrażenia',()=>{const s=new Simulation();flat(s);const enemy=s.npcs.find(n=>n.faction==='de');enemy.pos={x:0,y:0,z:4};s.actors=[enemy];s.collision.boxes=[{id:'wall',min:{x:-4,y:-1,z:1.5},max:{x:4,y:3,z:2.5}}];blast(s,{x:0,y:.4,z:0},7,190,s.player);assert.equal(enemy.hp,100);s.collision.boxes=[];blast(s,{x:0,y:.4,z:0},7,190,s.player);assert.ok(enemy.hp<100);});
test('zauważony granat zmienia stan NPC na unikanie zagrożenia',()=>{const s=new Simulation();flat(s);s.director.phase=1;const n=s.npcs[0];n.pos={x:0,y:0,z:10};n.think=0;s.grenades.push({id:'g',pos:{x:1,y:.2,z:10},fuse:2});updateSoldier(s,n,1/60);assert.equal(n.state,'evade');assert.equal(n.pathPending,true);});
test('martwy NPC nie strzela, nie przeładowuje i nie nawiguje',()=>{const s=new Simulation();s.director.phase=1;const n=s.npcs[0];n.hp=0;n.weapon.mag=0;n.weapon.reload();const left=n.weapon.reloadLeft;updateSoldier(s,n,1);assert.equal(n.state,'dead');assert.equal(n.weapon.reloadLeft,left);assert.equal(s.stats.britishShots,0);});
test('obie strony walczą przez 60 sekund bez strzelającego gracza',()=>{const s=new Simulation();s.interact();for(let i=0;i<3600;i++)s.tick(1/60,{});assert.ok(s.stats.britishShots>10);assert.ok(s.stats.germanShots>10);assert.equal(s.stats.playerShots,0);assert.ok(s.stats.reloads>0);assert.ok(s.stats.enemyLost>0);assert.ok(s.stats.alliedLost>0||s.npcs.some(n=>n.faction==='uk'&&n.hp<100));assert.ok(s.npcs.some(n=>n.travel>10));});
test('kontratak nie duplikuje żołnierzy ani zdarzeń po przywróceniu snapshotu',()=>{const s=new Simulation();s.director.phase=5;s.director.events=['assault'];s.director.advance(s);const count=s.npcs.length;s.director.checkpointPending=false;const saved=s.snapshot(),restored=new Simulation(saved);assert.equal(count,38);assert.equal(restored.npcs.length,count);assert.equal(restored.director.once('counterattack'),false);assert.equal(restored.npcs.filter(n=>n.id.startsWith('de-counter')).length,8);});
test('zapis odtwarza część czasu obrony oraz stan unieruchomionego czołgu',()=>{const s=new Simulation();s.director.phase=6;s.director.events=['assault','counterattack'];s.director.hold=17.5;s.tanks[1].state='immobilized';const restored=new Simulation(s.snapshot());assert.equal(restored.director.hold,17.5);assert.equal(restored.tanks[1].state,'immobilized');});
test('uszkodzony timer AI i amunicja NPC są odrzucane przed odtworzeniem',()=>{const s=new Simulation().snapshot();s.npcs[0].weapon.reserve=-1;assert.throws(()=>validateSnapshot(s));});
test('zmiana do leżenia wymaga miejsca przed głową i za nogami',()=>{const s=new Simulation();flat(s);s.collision.boxes=[{id:'tight',min:{x:-1,y:0,z:.4},max:{x:1,y:3,z:1}}];assert.equal(s.collision.canStand(s.player.pos,'stand',0),true);assert.equal(s.collision.canStand(s.player.pos,'prone',0),false);});
test('obie trasy czołgów kończą się bez blokady statycznym drutem',()=>{const s=new Simulation();s.director.skipBriefing(s);s.director.events.push('mg-silenced','fieldgun-silenced');s.npcs=[];s.actors=[s.player];for(let i=0;i<15600;i++)s.tick(1/60,{});for(const t of s.tanks){assert.equal(t.state,'holding');assert.equal(t.routeIndex,t.route.length);assert.ok(t.pos.z>158);}assert.equal(s.destroyedObstacles.length,2);});
// Static-route regression: start after the new physical doors have opened.
// Live-body avoidance is tested separately in v03-world.
test('normalny ruch gracza przechodzi grafem przez okopy i boczny łącznik',()=>{const s=new Simulation();s.collision.actors=[s.player];s.director.skipBriefing(s);s.time+=1;s.refreshDynamic();for(const goal of [{x:6,z:48},{x:23,z:62},{x:-27,z:69},{x:4,z:159}]){const path=s.nav.path(s.player.pos,goal);assert.ok(path.length>0);for(const waypoint of path){let steps=0;while(Math.hypot(waypoint.x-s.player.pos.x,waypoint.z-s.player.pos.z)>.3&&steps++<300){s.player.yaw=Math.atan2(waypoint.x-s.player.pos.x,waypoint.z-s.player.pos.z);s.player.update(s,1/60,{forward:true});}assert.ok(steps<300,`Zablokowany ruch przy ${JSON.stringify(s.player.pos)}`);}assert.ok(Math.hypot(goal.x-s.player.pos.x,goal.z-s.player.pos.z)<1.8);}});
