import test from 'node:test';import assert from 'node:assert/strict';
let modules;
async function load(){return modules??=Promise.all([import('../src/performance/monitor.js'),import('../src/performance/gpu-timer.js')]);}
function fakeGL(supported=true){let active=null;const deleted=[],queries=[];const ext={GPU_DISJOINT_EXT:42,TIME_ELAPSED_EXT:43};return {queries,deleted,disjoint:false,QUERY_RESULT_AVAILABLE:1,QUERY_RESULT:2,getExtension:()=>supported?ext:null,isContextLost:()=>false,getParameter(){return this.disjoint;},createQuery(){const q={ready:false,ns:2_500_000};queries.push(q);return q;},beginQuery(_,q){assert.equal(active,null);active=q;},endQuery(){assert.ok(active);active=null;},getQueryParameter(q,kind){return kind===1?q.ready:q.ns;},deleteQuery(q){assert.ok(!deleted.includes(q));deleted.push(q);}};}
test('CPU work and frame interval are independent, with bounded history',async()=>{const [{PerformanceMonitor}]=await load();const p=new PerformanceMonitor(4,0);for(let i=1;i<=6;i++)p.record({frame:20,cpu:3,simulation:1,render:2},i*20);assert.equal(p.metrics.fps,50);assert.equal(p.metrics.cpu,3);assert.equal(p.metrics.frame,20);assert.equal(p.metrics.p95,20);assert.equal(p.count,4);p.reset();assert.equal(p.count,0);assert.equal(p.metrics.fps,0);});
test('unavailable GPU timer never fabricates milliseconds',async()=>{const [,{GpuTimer}]=await load();const gl=fakeGL(false),timer=new GpuTimer(gl);timer.setEnabled(true);timer.begin();timer.end();assert.equal(timer.milliseconds,null);assert.equal(timer.status,'unsupported');assert.equal(gl.queries.length,0);timer.dispose();});
test('GPU query is read only when available and nanoseconds become milliseconds',async()=>{const [,{GpuTimer}]=await load();const gl=fakeGL(),timer=new GpuTimer(gl,{sampleEvery:1});timer.setEnabled(true);timer.begin();timer.end();timer.poll();assert.equal(timer.milliseconds,null);gl.queries[0].ready=true;timer.poll();assert.equal(timer.milliseconds,2.5);assert.equal(gl.deleted.length,1);timer.dispose();});
test('GPU disjoint discards pending results and invalidates the old sample',async()=>{const [,{GpuTimer}]=await load();const gl=fakeGL(),timer=new GpuTimer(gl,{sampleEvery:1});timer.setEnabled(true);timer.begin();timer.end();gl.disjoint=true;timer.poll();assert.equal(timer.milliseconds,null);assert.equal(timer.status,'disjoint');assert.equal(gl.deleted.length,1);gl.disjoint=false;timer.begin();timer.end();gl.queries.at(-1).ready=true;timer.poll();assert.equal(timer.milliseconds,2.5);timer.dispose();});
test('query queue is bounded and fully disposed on disable',async()=>{const [,{GpuTimer}]=await load();const gl=fakeGL(),timer=new GpuTimer(gl,{sampleEvery:1,maxPending:3});timer.setEnabled(true);for(let i=0;i<25;i++){timer.begin();timer.end();}assert.equal(gl.queries.length,3);timer.setEnabled(false);assert.equal(gl.deleted.length,3);assert.equal(timer.milliseconds,null);timer.dispose();assert.equal(gl.deleted.length,3);});
