// Revision 2: the radius-boundary fixture is now (60, 0), not a square-corner point.
import test from 'node:test';import assert from 'node:assert/strict';import {TacticalContacts,normalizeShot} from '../src/ui/hud/tactical-contacts.js';
const ctx=difficultyId=>({sessionId:1,playerFaction:'uk',playerPos:{x:0,y:0,z:0},difficultyId});const shot=(time,x=10,owner='de-4')=>({owner,faction:'de',pos:{x,y:1.5,z:20},time});
for(const [id,ttl] of [['recruit',3],['soldier',2],['veteran',1]])test(`contact expires exactly at ${ttl}s for ${id}`,()=>{const c=new TacticalContacts({sessionId:1});c.recordShot(shot(10),ctx(id));assert.equal(c.sample(10+ttl-.001).length,1);assert.equal(c.sample(10+ttl).length,0);});
test('positions are detached from both emitter and consumer',()=>{const c=new TacticalContacts({sessionId:1}),e=shot(10);c.recordShot(e,ctx('soldier'));e.pos.x=45;const a=c.sample(10.2);assert.equal(a[0].pos.x,10);a[0].pos.x=-20;assert.equal(c.sample(10.3)[0].pos.x,10);});
test('one shooter, monotonically latest event time, no receive-time renewal',()=>{const c=new TacticalContacts({sessionId:1});c.recordShot(shot(10),ctx('soldier'));c.recordShot(shot(11,20),ctx('soldier'));c.recordShot(shot(10.5,5),ctx('soldier'));assert.equal(c.sample(12.9)[0].expiresAt,13);assert.equal(c.sample(12.9)[0].pos.x,20);assert.equal(c.sample(13).length,0);});
test('pause, new generation and range gating never resurrect remote shots',()=>{const c=new TacticalContacts({sessionId:1});c.recordShot(shot(10),ctx('veteran'));for(let i=0;i<1800;i++)assert.equal(c.sample(10.5).length,1);c.reset(2);assert.equal(c.recordShot(shot(10),ctx('soldier')),false);c.reset(1);assert.equal(c.recordShot(shot(10,60.01),ctx('soldier')),false);assert.equal(c.recordShot({...shot(10),faction:'uk'},ctx('soldier')),false);assert.equal(c.recordShot({...shot(10,60),pos:{x:60,y:1.5,z:0}},ctx('soldier')),true);});
test('invalid, stale and repeated inputs cannot grow the bounded ledger',()=>{const c=new TacticalContacts({sessionId:1,maxContacts:4});for(const e of [shot(NaN),shot(10,Infinity),{...shot(10),owner:''},{...shot(10),faction:''}])assert.equal(c.recordShot(e,ctx('soldier')),false);for(let i=0;i<20;i++)c.recordShot(shot(10+i*.01,10,`de-${i}`),ctx('soldier'));assert.equal(c.sample(10.3).length,4);assert.equal(c.overflow,16);c.sample(30);assert.equal(c.recordShot(shot(10),ctx('soldier')),false);});
test('only real shot/cannon events normalize to revealing contacts',()=>{for(const type of ['impact','explosion','reload','air-warning','dryfire'])assert.equal(normalizeShot({type,...shot(1)}),null);assert.equal(normalizeShot({type:'cannon',...shot(1)}).owner,'de-4');assert.equal(normalizeShot({type:'shot',owner:'de-4',faction:'de',from:{x:1,y:2,z:3},time:1}).pos.z,3);});
