import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {Store} from '../src/save/store.js';
import {createProgress} from '../src/save/campaign.js';
const cp=()=>JSON.parse(readFileSync(new URL('./fixtures/v041-checkpoint.json',import.meta.url)));
function database(){const records=new Map(),calls=[];let fail=false;return{records,calls,failNext(){fail=true;},transaction(name,mode){const tx={error:null},pending=new Map();calls.push({name,mode,pending});let cancelled=false;
 const finish=()=>{if(cancelled)return;if(fail&&mode==='readwrite'){fail=false;tx.error=new Error('injected abort');tx.onabort?.();return;}for(const [k,v] of pending)records.set(k,v);tx.oncomplete?.();};
 tx.objectStore=()=>({put(value,key){pending.set(key,structuredClone(value));},get(key){const q={};queueMicrotask(()=>{q.result=structuredClone(records.get(key));q.onsuccess?.();});return q;}});tx.abort=()=>{cancelled=true;queueMicrotask(()=>tx.onabort?.());};queueMicrotask(()=>queueMicrotask(finish));return tx;}};}
test('checkpoint and progress commit and read in single transactions',async()=>{const db=database(),s=new Store(()=>{});s.db=async()=>db;const a=cp(),p=createProgress(a,'one');assert.equal(await s.saveCampaign(a,p),true);assert.equal(db.calls.length,1);assert.deepEqual([...db.calls[0].pending.keys()],['checkpoint','campaign-progress-v1']);const loaded=new Store(()=>{});loaded.db=async()=>db;const pair=await loaded.loadCampaign();assert.equal(pair.progress.runId,'one');assert.deepEqual(pair.checkpoint,a);assert.equal(db.calls.at(-1).mode,'readonly');});
test('failed transaction keeps both durable old records while session can use the new pair',async()=>{const db=database(),s=new Store(()=>{});s.db=async()=>db;const a=cp();await s.saveCampaign(a,createProgress(a,'old'));db.failNext();const b=cp();b.player.grenades=1;assert.equal(await s.saveCampaign(b,createProgress(b,'new')),false);assert.equal(db.records.get('campaign-progress-v1').runId,'old');assert.equal(db.records.get('checkpoint').player.grenades,a.player.grenades);const r=await s.loadCampaign();assert.equal(r.progress.runId,'new');assert.equal(r.sessionOnly,true);});
test('cancelled candidate cannot replace an older accepted session pair',async()=>{const db=database(),s=new Store(()=>{});s.db=async()=>db;const a=cp();await s.saveCampaign(a,createProgress(a,'old'));let resolve;const gate=new Promise(r=>resolve=r);s.db=()=>gate;const pending=s.saveCampaign(a,createProgress(a,'new'));s.invalidatePending();resolve(db);await pending;assert.equal((await s.loadCampaign()).progress.runId,'old');assert.equal(db.records.get('campaign-progress-v1').runId,'old');});
test('synchronous failure of the second put aborts the first put too',async()=>{
 const a=cp(),old=createProgress(a,'old'),durable=new Map([['checkpoint',a],['campaign-progress-v1',old]]);let aborted=false;
 const s=new Store(()=>{});s.db=async()=>({transaction(){const pending=new Map(),tx={objectStore:()=>({put(value,key){if(key==='campaign-progress-v1')throw Error('DataCloneError');pending.set(key,structuredClone(value));}}),abort(){aborted=true;}};queueMicrotask(()=>{if(!aborted){for(const [k,v] of pending)durable.set(k,v);tx.oncomplete?.();}else tx.onabort?.();});return tx;}});
 const b=cp();b.player.grenades=1;assert.equal(await s.saveCampaign(b,createProgress(b,'new')),false);assert.equal(aborted,true);assert.equal(durable.get('checkpoint').player.grenades,3);assert.equal(durable.get('campaign-progress-v1').runId,'old');assert.equal((await s.loadCampaign()).progress.runId,'new');
});
