import test from 'node:test';import assert from 'node:assert/strict';import {GpuTimer} from '../src/performance/gpu-timer.js';
function gl(){let active;return{qs:[],lost:false,disjoint:false,QUERY_RESULT_AVAILABLE:1,QUERY_RESULT:2,getExtension:()=>({TIME_ELAPSED_EXT:3,GPU_DISJOINT_EXT:4}),createQuery(){const q={ready:false,ns:6e6};this.qs.push(q);return q;},isContextLost(){return this.lost;},beginQuery(_,q){assert.ok(!active);active=q;},endQuery(){active=null;},deleteQuery(q){assert.ok(!q.deleted);q.deleted=true;},getParameter(){return this.disjoint;},getQueryParameter(q,k){if(k===2)assert.ok(q.ready,'blocking read');return k===1?q.ready:q.ns;}};}
test('v045 GPU: each result carries original frame/session and is drained once',()=>{const g=gl(),t=new GpuTimer(g,{sampleEvery:1});assert.equal(typeof t.drainSamples,'function');t.setEnabled(true,4);t.begin(10,{frameId:7,sessionId:4});t.end();t.poll(11);assert.deepEqual(t.drainSamples(),[]);g.qs[0].ready=true;t.poll(20);assert.deepEqual(t.drainSamples(),[{frameId:7,sessionId:4,submittedAt:10,milliseconds:6}]);assert.deepEqual(t.drainSamples(),[]);t.dispose();});
test('v045 GPU: switching session, disjoint and lost context discard results',()=>{const g=gl(),t=new GpuTimer(g,{sampleEvery:1});assert.equal(typeof t.drainSamples,'function');t.setEnabled(true,1);t.begin(10,{frameId:1,sessionId:1});t.end();t.setEnabled(true,2);g.qs[0].ready=true;t.poll(12);assert.deepEqual(t.drainSamples(),[]);t.begin(20,{frameId:2,sessionId:2});t.end();g.disjoint=true;t.poll(25);assert.deepEqual(t.drainSamples(),[]);assert.equal(t.status,'disjoint');g.disjoint=false;g.lost=true;t.poll(30);assert.equal(t.status,'context-lost');t.dispose();});
test('v045 GPU: default query cadence cycles 3/4/5, not a phase-locked every third frame',()=>{
 const g=gl(),timer=new GpuTimer(g);timer.setEnabled(true,1);const frames=[];
 for(let f=0;f<24;f++){timer.begin(f*6,{frameId:f,sessionId:1});if(timer.active)frames.push(f);timer.end();for(const q of g.qs)q.ready=true;timer.poll(f*6+1);timer.drainSamples();}
 assert.deepEqual(frames.slice(0,7),[0,3,7,12,15,19]);timer.dispose();
});
