import test from 'node:test';
import assert from 'node:assert/strict';
import {Terrain} from '../src/world/terrain.js';
import {makeLayout} from '../src/world/layout.js';
import {CollisionWorld} from '../src/world/collision.js';
import {Navigation} from '../src/ai/navigation.js';
import {Simulation} from '../src/core/simulation.js';
const terrain=new Terrain(),collision=new CollisionWorld(terrain,makeLayout(terrain));
test('okop ma rzeczywiste obniżenie',()=>{assert.ok(terrain.height(0,3)<terrain.height(0,20)-1.5);});
test('graf nie wyznacza przejścia przez ścianę schronu',()=>{const nav=new Navigation(collision);const route=nav.path({x:17,y:0,z:60},{x:23,y:0,z:62});assert.ok(route.length>0);let a=nav.nearest({x:17,z:60}).pos;for(const b of route){assert.ok(collision.canWalk(a,b));a=b;}});
test('misja rozpoczyna się bez natarcia i z 38 NPC (w tym obsługa i rezerwa)',()=>{const s=new Simulation();assert.equal(s.npcs.length,38);assert.equal(s.director.phase,0);const z=s.tanks[0].pos.z;s.tick(1/60,{});assert.equal(s.tanks[0].pos.z,z);});
test('zapis odtwarza zużyty przedmiot i nie powiela amunicji',()=>{const s=new Simulation();s.items[0].used=true;s.player.weapons[0].fire();s.director.events.push('assault');s.director.phase=2;const snapshot=s.snapshot();const loaded=new Simulation(snapshot);assert.equal(loaded.player.weapons[0].mag,9);assert.equal(loaded.items[0].used,true);assert.deepEqual(loaded.director.events,['assault']);assert.equal(loaded.npcs.length,38);});
test('granat wybucha tylko raz',()=>{const s=new Simulation();s.grenades.push({id:'test',owner:'player',faction:'uk',pos:{x:40,y:1,z:20},vel:{x:0,y:0,z:0},fuse:.001});s.tick(1/60,{});assert.equal(s.grenades.length,0);const e=s.events.filter(e=>e.type==='explosion').length;s.tick(1/60,{});assert.equal(s.events.filter(e=>e.type==='explosion').length,e);});
test('ogień obu stron powoduje prawdziwe obrażenia',()=>{const s=new Simulation();const target=s.npcs.find(n=>n.faction==='de');s.damage(target,100,s.npcs[0]);assert.equal(target.hp,28);s.damage(target,100,s.npcs[0]);assert.equal(target.hp,0);assert.equal(target.state,'dead');s.damage(s.npcs[0],80,s.player);assert.equal(s.npcs[0].hp,100);});
