import {PHASE} from '../data/briefing.js';
import {damageFeedback} from './damage-feedback.js';
import {MAP_SVG} from './map.js';
import {CAMPAIGN} from '../data/cambrai.js';
import {DEFAULT_KEYS} from '../save/store.js';
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const keyLabel=code=>String(code).replace(/^Key/,'').replace(/^Digit/,'').replace('ShiftLeft','Shift').replace('ShiftRight','Shift P').replace('Space','Spacja').replace('ControlLeft','Ctrl').replace('ControlRight','Ctrl P').replace('Arrow','');
const keyNames={forward:'Ruch do przodu',back:'Ruch do tyłu',left:'Ruch w lewo',right:'Ruch w prawo',sprint:'Sprint',crouch:'Kucanie',prone:'Leżenie',jump:'Skok / niska przeszkoda',interact:'Interakcja',reload:'Przeładowanie',grenade:'Granat',melee:'Walka wręcz',slot1:'Pierwsza broń',slot2:'Druga broń'};
const primary=(text,action)=>`<button class="button-primary" data-action="${action}">${text}<span class="arrow">→</span></button>`;
const back=()=>'<button class="button-quiet back" data-action="back">← Wróć</button>';
const topbar=()=>'<header class="topbar"><div class="brand"><span class="roundel">Z</span>ZIEMIA NICZYJA</div><div>FRONT ZACHODNI &nbsp; / &nbsp; 1916—1918</div></header>';
const footer=()=>'<footer class="bottom-bar"><span>WERSJA 0.4.0 · PROTOTYP CAMBRAI</span><span>POJEDYNCZY GRACZ / WEBGL2</span></footer>';
export class UI {
 constructor(app){this.app=app;this.menu=document.querySelector('#menu');this.hud=document.querySelector('#hud');this.toastNode=document.querySelector('#toast');this.toastUntil=0;this.messageUntil=0;this.message='';this.checkpointUntil=0;this.debug=false;this.nextHud=0;this.nextDebug=0;this.nextPerformance=0;
  this.menu.addEventListener('click',e=>{const button=e.target.closest('[data-action]');if(button&&!button.disabled)this.app.action(button.dataset.action,button);});
  this.menu.addEventListener('input',e=>{if(e.target.dataset.setting){let value=e.target.type==='checkbox'?e.target.checked:(e.target.type==='range'||e.target.type==='number')?Number(e.target.value):e.target.value;this.app.changeSetting(e.target.dataset.setting,value);const output=e.target.closest('.setting')?.querySelector('.value');if(output)output.textContent=e.target.dataset.setting==='fov'?Math.round(value)+'°':Math.round(value*100)+'%';}});
  this.hud.innerHTML=`<div class="damage-vignette" id="damage"></div><div class="damage-direction" id="damage-direction"><span></span></div><div class="critical-health" id="critical-health">NISKIE ZDROWIE · ZNAJDŹ OSŁONĘ</div><div class="hud-goal"><div class="hud-label" id="goal-label">AKTUALNY CEL</div><div class="hud-objective" id="objective"></div><div class="hud-hint" id="hint"></div><div class="hud-hold" id="hold"><div id="hold-fill"></div></div></div><div class="compass" id="compass">· &nbsp; · &nbsp; <b>N</b> &nbsp; · &nbsp; ·</div><div class="hud-chapter">CAMBRAI<br>20 XI 1917</div><div class="crosshair" id="crosshair"></div><div class="health-panel"><div class="health-value"><span>ZDROWIE</span><span id="hp"></span></div><div class="health-bar"><div id="hp-fill"></div></div><div class="stamina-bar"><div id="stamina-fill"></div></div><div class="stance-label" id="stance"></div></div><div class="ammo-panel"><div class="ammo-number"><span id="mag"></span><span class="reserve">/ <span id="reserve"></span></span></div><div class="ammo-name" id="weapon-name"></div><div class="grenades" id="grenades"></div><div class="reload-status" id="reload"></div></div><div class="interaction" id="interaction" hidden></div><div class="subtitle-box" id="subtitle" hidden></div><div class="objective-marker" id="marker"><div class="marker-diamond"></div><div class="marker-distance" id="distance"></div></div><div class="grenade-warning" id="grenade-warning" hidden>GRANAT — ODSUŃ SIĘ</div><div class="checkpoint-flash" id="checkpoint" hidden></div><div class="debug-panel" id="debug" hidden></div><div class="performance-overlay" id="performance" hidden aria-label="Statystyki wydajności"></div><div class="hud-footer">ESC · PAUZA &nbsp;&nbsp; F3 · DIAGNOSTYKA &nbsp;&nbsp; WERSJA 0.4</div>`;
  this.el=Object.fromEntries([...this.hud.querySelectorAll('[id]')].map(e=>[e.id,e]));
 }
 render(state){this.nextHud=this.nextDebug=this.nextPerformance=0;const app=this.app,s=app.settings;this.menu.hidden=state==='playing';this.hud.hidden=state!=='playing';if(state==='playing')return;
  let body='',cls='panel-screen',narrow=false;
  if(state==='main'){this.menu.innerHTML=`<section class="screen main-screen">${topbar()}<div class="map-clip"><div class="map-wrap">${MAP_SVG}</div></div><div class="map-vignette"></div><main class="main-content"><div class="eyebrow">Zapiski z frontu zachodniego</div><h1 class="main-title">ZIEMIA<span>NICZYJA</span></h1><p class="subtitle">Nie zdobędziesz całego frontu.<br>Utrzymaj ten jeden odcinek.</p><div class="rule"></div><nav class="menu-actions">${primary('Rozpocznij misję pokazową','brief')}<button class="button-secondary" data-action="continue" ${app.checkpoint?'':'disabled'}>Kontynuuj od punktu zapisu</button><button class="button-secondary" data-action="missions">Wybór misji</button><button class="button-secondary" data-action="settings">Ustawienia</button><button class="button-secondary" data-action="controls">Sterowanie</button><button class="button-secondary" data-action="credits">O projekcie i zasobach</button></nav><div class="footnote">Wersja 0.4. Grywalna misja nr 04.<br>Pozostała kampania jest w przygotowaniu.<br>Zapis lokalny — usunięcie danych strony usuwa postęp.</div></main><aside class="dossier"><div class="eyebrow">Rozkaz operacyjny</div><span class="num">04</span><h2>Pęknięta linia</h2><p>Cambrai, Francja<br>20 listopada 1917<br>Brytyjska piechota · Thomas Reed</p><span class="stamp">DO RĄK WŁASNYCH</span></aside>${footer()}</section>`;return;}
  if(state==='missions'){body=`<div class="eyebrow">Kronika kampanii</div><h1>Pięć odcinków frontu.</h1><p class="lead">W tej wersji dostępna jest wyłącznie misja pokazowa Cambrai. Pozostałe rozdziały to plan kampanii, nie gotowe poziomy.</p><div class="missions">${CAMPAIGN.map(m=>`<button class="mission-card" data-action="brief" ${m.available?'':'disabled'}><span class="number">${m.number}</span><div><h3>${m.title}</h3><p>${m.place} · ${m.date}</p></div><span class="badge">${m.available?'GRYWALNY PROTOTYP':'PLANOWANA'}</span></button>`).join('')}</div>${back()}`;}
  if(state==='brief'){body=`<div class="eyebrow">Misja 04 / Odprawa</div><h1>Pęknięta linia</h1><p class="lead">20 listopada 1917 · Cambrai, Francja<br><strong>Szeregowy Thomas Reed, brytyjska piechota.</strong></p><div class="brief-grid"><div><p>Po przygotowaniu natarcia oddział sierżanta Hughesa ma przejść przez pierwszą linię, uciszyć karabin maszynowy i przywrócić łączność w zrujnowanym domu.</p><ol class="brief-list"><li>Wysłuchaj odprawy w stanowisku dowodzenia. E pozwala ją pominąć. Wyjście jest we wschodniej ścianie.</li><li>Wykorzystaj dwa Mark IV i obniżenia terenu. Schron można obejść od tyłu; lewa flanka prowadzi do łącznika.</li><li>Odbierz meldunek, ucisz działo zagrażające czołgom i uruchom telefon. Nie dopuść przeciwnika do ruin podczas kontrataku.</li></ol></div><aside class="brief-card"><h3>WYPOSAŻENIE I ROZKAZY</h3><p>SMLE Mk III · Webley Mk VI<br>3 granaty Mills<br>Lewis do podniesienia przy punkcie sanitarnym</p><p>Zdrowie regeneruje się po 6 sekundach bez obrażeń. Apteczki przywracają 50 HP.</p><div class="big-number">04</div></aside></div><p class="notice">Fikcyjny lokalny epizod w historycznej bitwie. Modele, animacje i balans są prototypowe. ${app.checkpoint?'Rozpoczęcie od nowa zastąpi bieżący checkpoint.':''}</p><div class="panel-actions">${primary('Wejdź na odprawę','start')}${back()}</div>`;}
  if(state==='settings'){const range=(key,label,min,max,step)=>`<div class="setting"><label for="set-${key}">${label}</label><div class="range-box"><input id="set-${key}" data-setting="${key}" type="range" min="${min}" max="${max}" step="${step}" value="${s[key]}"><span class="value">${key==='fov'?Math.round(s[key])+'°':Math.round(s[key]*100)+'%'}</span></div></div>`;
   body=`<div class="eyebrow">Dostosowanie</div><h1>Ustawienia</h1><p class="lead">Zmiany dźwięku i czułości działają od razu. Grafikę zastosujesz przy powrocie. Trudność dotyczy nowo rozpoczętej misji.</p><div class="settings-grid"><div class="setting"><label for="quality">Jakość grafiki</label><select id="quality" data-setting="quality">${[['low','Low · niska'],['medium','Medium · średnia'],['high','High · wysoka'],['ultra','Ultra · pełna']].map(([v,t])=>`<option value="${v}" ${s.quality===v?'selected':''}>${t}</option>`).join('')}</select></div><div class="setting"><label for="difficulty">Poziom trudności</label><select id="difficulty" data-setting="difficulty">${[['recruit','Rekrut'],['soldier','Żołnierz'],['veteran','Weteran']].map(([v,t])=>`<option value="${v}" ${s.difficulty===v?'selected':''}>${t}</option>`).join('')}</select></div><div class="setting"><label for="set-maxFps">Limit FPS · 0 = bez limitu aplikacji</label><input id="set-maxFps" type="number" min="0" max="360" step="1" list="fps-values" data-setting="maxFps" value="${s.maxFps}"><datalist id="fps-values">${[0,30,60,90,120,144,165,240].map(v=>`<option value="${v}"></option>`).join('')}</datalist></div>${range('renderScale' ,'Skala rozdzielczości',.5,1.25,.05)}${range('fov','Pole widzenia',60,105,1)}${range('sensitivity','Czułość myszy',.2,3,.05)}${range('motion','Kołysanie i odrzut kamery',0,1,.05)}${range('damageEffects','Intensywność efektów obrażeń',0,1,.05)}${range('master','Głośność główna',0,1,.05)}${range('effects','Efekty dźwiękowe',0,1,.05)}${range('ambient','Tło bitwy',0,1,.05)}<div class="setting"><label for="subtitles">Komunikaty oddziału</label><input type="checkbox" id="subtitles" data-setting="subtitles" ${s.subtitles?'checked':''}></div>${[['showFps','Pokaż FPS i czas klatki'],['showCpu','Pokaż czas CPU'],['showGpu','Pokaż czas GPU']].map(([key,label])=>`<div class="setting"><label for="set-${key}">${label}</label><input type="checkbox" id="set-${key}" data-setting="${key}" ${s[key]?'checked':''}></div>`).join('')}</div><p class="controls-note">Synchronizacją obrazu zarządza przeglądarka. 0 usuwa tylko limit gry; nie gwarantuje wyłączenia VSync. Limit nie zmienia tempa AI ani fizyki. Niższy limit niż odświeżanie monitora może powodować nierówne odstępy klatek.<br>CPU: zmierzona praca głównego wątku aplikacji, nie pełny czas klatki. GPU: asynchroniczny pomiar renderowania, tylko gdy przeglądarka udostępnia timer. Brak obsługi jest oznaczony kreską, nie zerem.</p><p class="notice">Presety zmieniają cienie (0 / 1024 / 2048 / 4096), mapy normalnych, LOD, trawę i efekty — nie przeciwników ani kolizje. Zapis pozostaje wyłącznie w tej przeglądarce. ${app.storageWarning?escape(app.storageWarning):''}</p><div class="panel-actions">${primary('Zastosuj i wróć','back')}<button class="button-quiet" data-action="settings-reset">Ustawienia domyślne</button></div>`;
  }
  if(state==='controls'){body=`<div class="eyebrow">Obsługa broni i poruszanie</div><h1>Sterowanie</h1><p class="lead">Kliknij przypisanie i naciśnij nowy klawisz. Escape anuluje zmianę. Zajęte przypisania są zamieniane miejscami.</p><div class="settings-grid">${Object.entries(keyNames).map(([key,name])=>`<div class="setting"><label>${name}</label><button class="setting-button" data-action="bind" data-key="${key}">${keyLabel(s.keys[key])}</button></div>`).join('')}</div><p class="controls-note">Mysz — rozglądanie · LPM — ogień · PPM — celowanie<br>Kółko myszy — zmiana broni · Esc — pauza · F3 — panel diagnostyczny<br>Blokada kursora wymaga kliknięcia przycisku wejścia do walki. Gra zatrzymuje się po zmianie karty lub utracie fokusu.</p><div class="panel-actions">${back()}<button class="button-quiet" data-action="keys-reset">Przywróć klawisze domyślne</button></div>`;}
  if(state==='credits'){body=`<div class="eyebrow">Archiwum projektu</div><h1>O wersji 0.4</h1><p class="lead">„Ziemia Niczyja” — prototyp jednoosobowego FPS-a z I wojny światowej. Wersja 0.4 przebudowuje odprawę i natarcie, udział czołgów, artylerię i lotnictwo; poprawia kolizje, worki oraz sterowanie podczas celowania. Nie jest ukończoną pięciomisjową kampanią.</p><div class="brief-grid"><div><h3 class="eyebrow">Kod i oprawa</h3><p>Babylon.js 8.46.2, lokalne moduły JavaScript oraz statyczny build Node.js. W tej wersji nie użyto Vite: paczki npm były niedostępne w środowisku przygotowania.</p><p>Oryginalne modele GLB, szkielety i animacje, proceduralne tekstury oraz dźwięki Web Audio. Nie wykorzystano zasobów komercyjnych gier. Sylwetki, przeładowania i szczegóły wyposażenia wymagają dalszego dopracowania.</p></div><div><h3 class="eyebrow">Historia a fikcja</h3><p>Cambrai i data natarcia są historyczne. Thomas Reed, Arthur Hughes, William Ellis i George Bennett, układ mapy oraz zadania są fikcyjne.</p><p>Regeneracja zdrowia, skrócony teren, zapasy amunicji i przydzielony Reedowi rewolwer są uproszczeniami rozgrywki.</p></div></div><p><a class="small-link" href="./ASSET_LICENSES.md" target="_blank" rel="noopener">Licencje i pochodzenie zasobów</a> &nbsp; · &nbsp; <a class="small-link" href="./docs/HISTORY.md" target="_blank" rel="noopener">Notatka historyczna</a> &nbsp; · &nbsp; <a class="small-link" href="./docs/KNOWN_ISSUES.md" target="_blank" rel="noopener">Znane ograniczenia</a></p>${back()}`;}
  if(state==='loading'){this.menu.innerHTML=`<section class="screen panel-screen">${topbar()}<div class="loading-block"><div class="eyebrow">20 listopada 1917</div><h1>Pęknięta linia</h1><div class="loading-title" id="load-text">Przygotowywanie misji…</div><div class="loading-track"><div id="load-progress"></div></div><p class="loading-tip">Okopy chronią przed ostrzałem, ale nie prowadzą wszędzie. Rozglądaj się za rampami i bocznymi łącznikami.</p><button class="button-quiet" data-action="exit">Anuluj i wróć do menu</button></div>${footer()}</section>`;return;}
  if(['ready','paused','dead','complete'].includes(state)){cls='overlay-shade';narrow=state!=='complete';const w=app.world;
   if(state==='ready'){body=`<div class="eyebrow">Cambrai · 20 listopada 1917</div><h1>Na stanowiska.</h1><p class="lead">Kliknij, aby przejąć kontrolę i włączyć dźwięk. Przeglądarka zablokuje kursor wewnątrz gry.</p><p>WASD — ruch · mysz — celowanie<br>${keyLabel(s.keys.interact)} — interakcja · ${keyLabel(s.keys.reload)} — przeładowanie · Esc — pauza</p>${app.lockMessage?`<p class="notice">${escape(app.lockMessage)}</p>`:''}<div class="panel-actions">${primary('Wejdź do walki','enter')}<button class="button-quiet" data-action="exit">Wróć do menu</button></div>`;}
   if(state==='paused'){body=`<div class="eyebrow">Symulacja zatrzymana</div><h1>Chwila wytchnienia.</h1><p class="lead">${escape(w?.director.objective.title)}</p><nav class="menu-actions">${primary('Wznów walkę','enter')}<button class="button-secondary" data-action="checkpoint">Wczytaj ostatni punkt zapisu</button><button class="button-secondary" data-action="settings">Ustawienia</button><button class="button-secondary" data-action="controls">Sterowanie</button><button class="button-secondary" data-action="exit">Wróć do menu głównego</button></nav><p class="saved-notice">Checkpoint: ${escape(app.checkpoint?.director.lastCheckpoint||'Początek misji')}</p>`;}
   if(state==='dead'){body=`<div class="eyebrow">Oddział stracił łącznika</div><h1>Poległeś.</h1><p class="lead">Szukaj obniżeń terenu i osłon. Po sześciu sekundach bez obrażeń zdrowie zacznie się regenerować.</p><p>Ostatni punkt: ${escape(app.checkpoint?.director.lastCheckpoint||'Początek misji')}</p><div class="panel-actions">${primary('Wróć do punktu zapisu','checkpoint')}<button class="button-quiet" data-action="exit">Menu główne</button></div>`;}
   if(state==='complete'){const accuracy=w?.stats.playerShots?Math.round(w.stats.hits/w.stats.playerShots*100):0;body=`<div class="eyebrow">Misja pokazowa zakończona / 04</div><h1>Meldunek dotarł.</h1><p class="lead">Telefon znów działa. Oddział utrzymał lokalny odcinek i przekazał położenie wysuniętych pozycji. To niewielki sukces w większej bitwie, nie zwycięstwo w całej wojnie.</p><div class="stats"><div><div class="stat-number">${Math.floor(w.time/60)}:${String(Math.floor(w.time%60)).padStart(2,'0')}</div><div class="stat-label">CZAS MISJI</div></div><div><div class="stat-number">${w.stats.kills}</div><div class="stat-label">WYELIMINOWANI PRZEZ GRACZA</div></div><div><div class="stat-number">${accuracy}%</div><div class="stat-label">CELNE STRZAŁY GRACZA</div></div></div><p>Cambrai rozpoczęło się brytyjskim natarciem z udziałem licznych czołgów Mark IV. Początkowe zdobycze nie oznaczały trwałego przełamania; późniejszy niemiecki kontratak zmienił sytuację.</p><p class="notice">To koniec zawartości wersji 0.4, nie finał kampanii. Somma, Flers-Courcelette, Ypres i Amiens pozostają do realizacji.</p><div class="panel-actions">${primary('Wróć do mapy kampanii','exit')}<button class="button-quiet" data-action="checkpoint">Powtórz od checkpointu</button></div>`;}
  }
  if(state==='error'){narrow=true;body=`<div class="eyebrow">Misja wstrzymana</div><h1>Nie udało się uruchomić gry.</h1><p class="lead">Sprawdź obsługę WebGL2 i akcelerację sprzętową. Wszystkie zasoby muszą być dostępne pod adresem tej strony.</p><p class="error-detail">${escape(app.errorMessage)}</p><div class="panel-actions">${primary('Spróbuj ponownie','retry')}<button class="button-quiet" data-action="exit">Wróć do menu</button></div>`;}
  this.menu.innerHTML=`<section class="screen ${cls}">${topbar()}<main class="panel ${narrow?'narrow':''}">${body}</main>${footer()}</section>`;
 }
 progress(text,fraction){const el=document.querySelector('#load-text'),bar=document.querySelector('#load-progress');if(el)el.textContent=text;if(bar)bar.style.width=Math.round(fraction*100)+'%';}
 toast(text,duration=6){this.toastNode.textContent=text;this.toastUntil=performance.now()+duration*1000;this.toastNode.classList.add('visible');}
 event(e){if(e.type==='message'||e.type==='air-warning'){this.message=e.text;this.messageUntil=e.time+8;}if(e.type==='toast'||e.type==='pickup')this.toast(e.text,3);if(e.type==='checkpoint'){this.checkpointUntil=e.time+5;this.el.checkpoint.textContent=`PUNKT ZAPISU · ${e.name}`;}}
 tickUI(){if(this.toastUntil&&performance.now()>this.toastUntil){this.toastNode.classList.remove('visible');this.toastUntil=0;}}
 text(id,value){const node=this.el[id],text=String(value);if(node.textContent!==text)node.textContent=text;}
 updatePerformance(view,metrics,now){
  const e=this.el.performance,s=this.app.settings;
  e.hidden=!(s.showFps||s.showCpu||s.showGpu);
  if(e.hidden||now<this.nextPerformance)return;
  this.nextPerformance=now+250;
  const lines=[];
  if(s.showFps)lines.push(`${metrics.fps.toFixed(0)} FPS · klatka ${metrics.frame.toFixed(1)} ms`);
  if(s.showCpu)lines.push(`CPU ${metrics.cpu.toFixed(2)} ms · sim ${metrics.simulation.toFixed(2)} / render ${metrics.render.toFixed(2)}`);
  if(s.showGpu){
   const timer=view.gpuTimer,status={unsupported:'brak timera w przeglądarce',waiting:'oczekiwanie na próbkę',disjoint:'pomiar unieważniony',disabled:'wyłączony','context-lost':'utrata kontekstu'};
   lines.push(timer.milliseconds===null?`GPU — (${status[timer.status]||timer.status})`:`GPU ${timer.milliseconds.toFixed(2)} ms`);
  }
  this.text('performance',lines.join('\n'));
 }
 update(world,view,metrics){
  const p=world.player,o=world.director.objective,e=this.el,now=performance.now();
  this.text('mag',String(p.weapon.mag).padStart(2,'0'));
  this.text('reserve',p.weapon.reserve);
  const crosshair='crosshair'+(p.ads?' ads':'')+(p.hitMarker>0?' hit':'');
  if(e.crosshair.className!==crosshair)e.crosshair.className=crosshair;
  const feedback=damageFeedback(p,world.time,this.app.settings.damageEffects);e.damage.style.opacity=feedback.vignette;e['damage-direction'].style.opacity=feedback.directionOpacity;e['damage-direction'].style.transform=`translate(-50%,-50%) rotate(${feedback.rotation}deg)`;e['critical-health'].hidden=p.hp>=30||this.app.settings.damageEffects===0;e['critical-health'].style.opacity=.5+feedback.pulse*.5;view.canvas.style.filter=feedback.saturation<.999?`saturate(${feedback.saturation})`:'none';
  this.updatePerformance(view,metrics,now);
  e.debug.hidden=!this.debug;
  if(now<this.nextHud)return;this.nextHud=now+50;
  this.text('objective',o.title);
  this.text('hint',o.hint.replaceAll('[E]',`[${keyLabel(this.app.settings.keys.interact)}]`).replace('naciśnij E',`naciśnij ${keyLabel(this.app.settings.keys.interact)}`));
  this.text('goal-label',`AKTUALNY CEL · ${Math.min(world.director.phase+1,7)}/7`);
  this.text('hp',Math.ceil(p.hp));e['hp-fill'].style.width=p.hp+'%';e['hp-fill'].style.background=p.hp<30?'#c98468':'#e0d9b5';
  e['stamina-fill'].style.width=p.stamina/6*100+'%';
  this.text('stance',{stand:'STOJĄC',crouch:'W KUCKI',prone:'LEŻĄC'}[p.stance]);
  this.text('weapon-name',p.weapon.definition.name);
  this.text('grenades',`MILLS × ${p.grenades} · ${keyLabel(this.app.settings.keys.grenade)}`);
  this.text('reload',p.weapon.reloadLeft>0?'PRZEŁADOWYWANIE…':p.weapon.mag===0?'BRAK NABOJÓW W MAGAZYNKU':p.weapon.cooldown>.28&&['smle','gewehr'].includes(p.weapon.id)?'PRACA ZAMKA':'');
  e.hold.hidden=world.director.phase!==PHASE.HOLD;if(world.director.contested)this.text('hint','POZYCJA ZAGROŻONA — wyprzyj przeciwnika z otoczenia telefonu.');e['hold-fill'].style.width=world.director.hold/55*100+'%';
  const context=world.interaction();e.interaction.hidden=!context;
  if(context){const html=`<span class="keycap">${keyLabel(this.app.settings.keys.interact)}</span>${escape(context.label)}`;if(e.interaction.innerHTML!==html)e.interaction.innerHTML=html;}
  const caption=world.director.caption(world),sub=caption?`${caption.speaker}\n${caption.text}`:this.message; e.subtitle.hidden=!this.app.settings.subtitles||(!caption&&(world.time>this.messageUntil||!sub));this.text('subtitle',sub);
  e.checkpoint.hidden=world.time>this.checkpointUntil;
  const marker=view.marker();e.marker.hidden=!marker.visible||marker.x<4||marker.x>96||marker.y<17||marker.y>85||marker.distance<6||(world.director.phase===PHASE.HOLD||world.director.phase===PHASE.BRIEFING);
  if(!e.marker.hidden){e.marker.style.left=marker.x+'%';e.marker.style.top=marker.y+'%';this.text('distance',Math.round(marker.distance)+' m');}
  e['grenade-warning'].hidden=!world.grenades.some(g=>Math.hypot(g.pos.x-p.pos.x,g.pos.z-p.pos.z)<8&&world.collision.visible({x:p.pos.x,y:p.pos.y+1,z:p.pos.z},g.pos));
  const dirs=['N','NE','E','SE','S','SW','W','NW'],dir=dirs[(Math.round(p.yaw/(Math.PI/4))%8+8)%8];
  if(this.lastCompass!==dir){this.lastCompass=dir;e.compass.innerHTML=`· &nbsp; · &nbsp; <b>${dir}</b> &nbsp; · &nbsp; ·`;}
  if(this.debug&&now>=this.nextDebug){
   this.nextDebug=now+250;
   const nearest=world.npcs.filter(n=>n.hp>0).sort((a,b)=>(a.pos.x-p.pos.x)**2+(a.pos.z-p.pos.z)**2-(b.pos.x-p.pos.x)**2-(b.pos.z-p.pos.z)**2).slice(0,6);
   const stats=view.renderStats,gpu=view.gpuTimer.milliseconds;
   this.text('debug',`DIAGNOSTYKA · F3
${metrics.fps.toFixed(0)} FPS | p95 klatki ${metrics.p95.toFixed(1)} ms
CPU ${metrics.cpu.toFixed(2)} ms | GPU ${gpu===null?'— ('+view.gpuTimer.status+')':gpu.toFixed(2)+' ms'}
CPU sim/audio ${metrics.simulation.toFixed(2)} | render ${metrics.render.toFixed(2)} ms
Draw calls ${stats.drawCalls} | trójkąty (z cieniami) ${stats.triangles}
Aktywne meshe ${stats.activeMeshes} | castery ${stats.shadowCasters||0}
LOD 0/1/2: ${stats.lodCounts?.join('/')} | animatables ${stats.activeAnimatables}
Symulacja ${world.time.toFixed(1)} s | faza ${world.director.phase}
UK ${world.npcs.filter(n=>n.faction==='uk'&&n.hp>0).length} / DE ${world.npcs.filter(n=>n.faction==='de'&&n.hp>0).length}
Kolejka tras ${world.nav.requests.length} | strzały UK/DE ${world.stats.britishShots}/${world.stats.germanShots}
${world.tanks.map(t=>`${t.id}: ${t.state} | pociski ${t.ammunition} | MG ${t.mgAmmo}`).join('\n')}
Działo ${world.fieldGuns[0]?.operational?'czynne':'wyłączone'} | samoloty ${world.air.planes.length}
Trafienia pancerza ${world.stats.tankHits} | otwarte przejścia ${world.destroyedObstacles.length}

${nearest.map(n=>`${n.id.padEnd(7)} ${n.state.padEnd(9)} HP${Math.ceil(n.hp)}
 cel:${n.targetId||'—'} trasa:${n.pathIndex}/${n.path.length}`).join('\n')}`);
  }
 }
}
