import {MAP} from '../data/world-map.js';
import {v3,flatDist} from '../core/math.js';
/** Static 2 m graph uses the exact collision field. A small binary heap keeps A* bounded. */
class Heap{constructor(){this.a=[];}push(id,score){const a=this.a;let i=a.length;a.push({id,score});while(i){const p=(i-1)>>1;if(a[p].score<=score)break;a[i]=a[p];i=p;}a[i]={id,score};}pop(){const a=this.a,first=a[0],last=a.pop();if(a.length){let i=0;while(i*2+1<a.length){let c=i*2+1;if(c+1<a.length&&a[c+1].score<a[c].score)c++;if(last.score<=a[c].score)break;a[i]=a[c];i=c;}a[i]=last;}return first.id;}get length(){return this.a.length;}}
export class Navigation {
 constructor(collision){this.collision=collision;this.step=2;this.minX=MAP.navMinX;this.minZ=MAP.navMinZ;this.nx=(MAP.navMaxX-MAP.navMinX)/2+1;this.nz=(MAP.navMaxZ-MAP.navMinZ)/2+1;this.nodes=[];this.requests=[];this.coverOwners=new Map();
  for(let z=0;z<this.nz;z++)for(let x=0;x<this.nx;x++){const px=this.minX+x*2,pz=this.minZ+z*2,p=v3(px,collision.ground(px,pz,collision.terrain.height(px,pz),.36),pz);this.nodes.push({id:z*this.nx+x,pos:p,valid:!collision.overlaps({...p,y:p.y+.04},1.65,.36,false),edges:null});}
  this.cover=[];for(const b of collision.boxes.filter(b=>b.cover)){for(const side of [-1,1])for(const off of [-.25,.25]){const p=v3(b.x+b.w*off,0,b.z+side*(b.d/2+1.15));p.y=collision.terrain.height(p.x,p.z);if(!collision.overlaps({...p,y:p.y+.03},1.1,.35,false))this.cover.push({id:`${b.id}:${side}:${off}`,pos:p,side,owner:null});}}
 }
 nearest(p,reachable=false){let best=null,score=Infinity;const ix=Math.round((p.x-this.minX)/2),iz=Math.round((p.z-this.minZ)/2);for(let r=0;r<=5;r++){for(let dz=-r;dz<=r;dz++)for(let dx=-r;dx<=r;dx++){const x=ix+dx,z=iz+dz;if(x<0||z<0||x>=this.nx||z>=this.nz)continue;const n=this.nodes[z*this.nx+x];if(!n.valid||this.collision.dynamicBlocked(n.pos,n.pos))continue;const d=flatDist(p,n.pos);if(d<score&&(!reachable||this.collision.canWalk(p,n.pos,.36))){best=n;score=d;}}if(best&&score<r*2+.1)break;}return best;}
 edges(n){if(n.edges)return n.edges;n.edges=[];const x=n.id%this.nx,z=Math.floor(n.id/this.nx);for(let dz=-1;dz<=1;dz++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dz)continue;const nx=x+dx,nz=z+dz;if(nx<0||nz<0||nx>=this.nx||nz>=this.nz)continue;const other=this.nodes[nz*this.nx+nx];if(other.valid&&this.collision.canWalk(n.pos,other.pos,.36))n.edges.push({id:other.id,cost:Math.hypot(dx,dz)*2+Math.abs(other.pos.y-n.pos.y)*.7});}return n.edges;}
 path(from,to){const start=this.nearest(from,true),goal=this.nearest(to);if(!start||!goal)return[];const open=new Heap(),cost=new Float32Array(this.nodes.length);cost.fill(Infinity);const prev=new Int32Array(this.nodes.length);prev.fill(-1);const closed=new Uint8Array(this.nodes.length);cost[start.id]=0;open.push(start.id,0);let count=0,found=false;while(open.length&&count++<12000){const id=open.pop();if(closed[id])continue;if(id===goal.id){found=true;break;}closed[id]=1;for(const e of this.edges(this.nodes[id])){if(this.collision.dynamicBlocked(this.nodes[id].pos,this.nodes[e.id].pos))continue;const g=cost[id]+e.cost;if(g<cost[e.id]){cost[e.id]=g;prev[e.id]=id;open.push(e.id,g+flatDist(this.nodes[e.id].pos,goal.pos));}}}if(!found)return[];const result=[];for(let i=goal.id;i!==start.id&&i>=0;i=prev[i])result.push({...this.nodes[i].pos});result.reverse();if(flatDist(from,start.pos)>.15)result.unshift({...start.pos});return result;}
 request(actor,target){if(actor.pathPending)return;actor.pathPending=true;this.requests.push({actor,target:{...target}});}
 process(limit=2){while(limit--&&this.requests.length){const {actor,target}=this.requests.shift();actor.pathPending=false;if(actor.hp<=0)continue;actor.path=this.path(actor.pos,target);actor.pathTarget=target;actor.pathIndex=0;}}
 chooseCover(actor,threat){let best=null,score=Infinity;for(const c of this.cover){if(c.owner&&c.owner!==actor.id)continue;const d=flatDist(actor.pos,c.pos);if(d>17||d<.5)continue;const hidden=!this.collision.visible(v3(c.pos.x,c.pos.y+.8,c.pos.z),v3(threat.x,threat.y+1.4,threat.z));if(!hidden)continue;const s=d+flatDist(c.pos,threat)*.04;if(s<score){const route=this.path(actor.pos,c.pos);if(route.length){best=c;score=s;}}}if(best){this.releaseCover(actor.id);best.owner=actor.id;}return best;}
 releaseCover(id){for(const c of this.cover)if(c.owner===id)c.owner=null;}
}
