import {DIFFICULTIES} from '../../data/weapons.js';import {VERSION} from '../../version.js';import {message} from '../../i18n/index.js';import {checkpointKey} from '../../i18n/legacy.js';
import {tr,html,primary,button,quiet,shell} from '../common.js';
export function statusScreen(state,app){
 const w=app.world,profile=w?.difficulty||DIFFICULTIES[app.settings.difficulty]||DIFFICULTIES.soldier;
 const cp=message(checkpointKey(app.checkpoint?.director.lastCheckpoint));let body='';
 if(state==='loading')return shell(`<div class="loading-block"><h1>${tr('campaign.cambrai.title')}</h1><p class="loading-lead">${tr('loading.initial')}</p><div id="load-text" role="status">${tr('loading.runtime')}</div><div class="loading-track" role="progressbar" aria-label="${tr('loading.initial')}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div id="load-progress"></div></div><p class="loading-tip">${tr('loading.tip')}</p><div class="loading-actions">${quiet('action.cancel','cancel-loading')}</div></div>`,{narrow:true,variant:'loading-screen'});
 if(state==='ready')body=`<h1>${tr('ready.title')}</h1><p class="lead">${tr('ready.lead')}</p><p>${tr('mission.difficulty',{difficulty:profile.name})}</p>${app.lockMessage?`<p class="compact-error">${html(app.lockMessage)}</p>`:''}<div class="panel-actions">${primary('action.enter','enter')}${quiet('action.exit','exit')}</div>`;
 if(state==='paused')body=`<h1>${tr('paused.title')}</h1><p class="lead">${html(w?.director.objective.title)}</p><p>${tr('mission.difficulty',{difficulty:profile.name})}</p><nav class="menu-actions">${primary('action.resume','enter')}${button('action.loadCheckpoint','checkpoint',{disabled:!app.checkpoint})}${button('action.settings','settings')}${button('action.exitMain','exit')}</nav><p class="compact-help">${tr('checkpoint.label',{name:cp})}</p>`;
 if(state==='dead')body=`<h1>${tr('dead.title')}</h1><p class="lead">${tr('dead.advice',{difficulty:profile.name,delay:profile.regenDelay,rate:profile.regenRate})}</p><p>${tr('checkpoint.last',{name:cp})}</p><div class="panel-actions">${primary('action.respawn','checkpoint',!app.checkpoint)}${quiet('action.main','exit')}</div>`;
 if(state==='complete'){const stats=w?.stats||{},time=w?.time||0;body=`<h1>${tr('complete.title')}</h1><p class="lead">${tr('complete.lead')}</p><div class="stats">${[[`${Math.floor(time/60)}:${String(Math.floor(time%60)).padStart(2,'0')}`,'complete.time'],[stats.kills||0,'complete.kills'],[`${stats.playerShots?Math.round(stats.hits/stats.playerShots*100):0}%`,'complete.accuracy']].map(([v,k])=>`<div><strong>${html(v)}</strong><span>${tr(k)}</span></div>`).join('')}</div><p>${tr('complete.notice',{version:VERSION})}</p><div class="panel-actions">${primary('action.map','campaign-complete',!!app.completionPending)}${button('action.main','exit',{kind:'quiet',disabled:!!app.completionPending})}</div>${app.completionPending?`<p role="status">${tr('campaign.saving')}</p>`:''}`;}
 if(state==='error')body=`<h1>${tr('error.title')}</h1><p class="lead">${tr('error.lead')}</p><p class="error-detail">${html(app.errorMessage)}</p><div class="panel-actions">${primary('action.retry','retry')}${quiet('action.exit','exit')}</div>`;
 return shell(body,{narrow:state!=='complete',overlay:['ready','paused','dead','complete'].includes(state)});
}
